import type { AnySchemaObject } from "ajv";

export const schemaNames = [
  "milestone",
  "canonicalWorkArtifact",
  "epic",
  "workItem",
  "executionSet",
  "projectProfile",
  "canonicalEvent",
] as const;

export type SchemaName = (typeof schemaNames)[number];

const nonEmptyString = { type: "string", minLength: 1 } as const;
const stringArray = {
  type: "array",
  items: nonEmptyString,
} as const;
const boardStatus = [
  "To Do",
  "In Progress",
  "Review",
  "Ready for Deploy",
  "Ready for Test",
  "Testing",
  "Done",
] as const;

export const canonicalSchemas: Record<SchemaName, AnySchemaObject> = {
  canonicalWorkArtifact: {
    $id: "canonicalWorkArtifact",
    type: "object",
    additionalProperties: false,
    required: [
      "artifactId",
      "milestoneId",
      "vision",
      "scope",
      "nonGoals",
      "requirements",
      "implementationPlan",
      "testPlan",
      "acceptanceCriteria",
      "reviewPoints",
      "decisions",
      "evidenceRefs",
      "unknowns",
      "dependencies",
      "projectContext",
      "currentState",
    ],
    properties: {
      artifactId: nonEmptyString,
      milestoneId: nonEmptyString,
      vision: nonEmptyString,
      scope: stringArray,
      nonGoals: stringArray,
      requirements: stringArray,
      implementationPlan: stringArray,
      testPlan: stringArray,
      acceptanceCriteria: stringArray,
      reviewPoints: stringArray,
      decisions: stringArray,
      evidenceRefs: stringArray,
      unknowns: stringArray,
      dependencies: stringArray,
      projectContext: nonEmptyString,
      currentState: nonEmptyString,
    },
  },
  milestone: {
    $id: "milestone",
    type: "object",
    additionalProperties: false,
    required: [
      "canonicalId",
      "summary",
      "description",
      "parentCanonicalId",
      "boardStatus",
    ],
    properties: {
      canonicalId: nonEmptyString,
      summary: nonEmptyString,
      description: { $ref: "canonicalWorkArtifact" },
      parentCanonicalId: { type: "null" },
      boardStatus: { enum: boardStatus },
    },
  },
  epic: {
    $id: "epic",
    type: "object",
    additionalProperties: false,
    required: ["canonicalId", "summary", "parentMilestoneId", "boardStatus"],
    properties: {
      canonicalId: nonEmptyString,
      summary: nonEmptyString,
      parentMilestoneId: nonEmptyString,
      boardStatus: { enum: boardStatus },
    },
  },
  workItem: {
    $id: "workItem",
    type: "object",
    additionalProperties: false,
    required: [
      "canonicalId",
      "type",
      "summary",
      "parentEpicId",
      "boardStatus",
      "acceptanceCriteria",
    ],
    properties: {
      canonicalId: nonEmptyString,
      type: { enum: ["story", "task", "bug"] },
      summary: nonEmptyString,
      parentEpicId: nonEmptyString,
      boardStatus: { enum: boardStatus },
      acceptanceCriteria: stringArray,
    },
  },
  executionSet: {
    $id: "executionSet",
    type: "object",
    additionalProperties: false,
    required: [
      "executionSetId",
      "epicId",
      "workItemIds",
      "owner",
      "agentHost",
      "jiraProjectKey",
      "jiraBoardId",
      "branchName",
      "worktreePath",
      "baseRevision",
      "affectedPaths",
      "dependencyIds",
      "acceptanceBoundary",
      "targetEnvironment",
      "pullRequestUrls",
    ],
    properties: {
      executionSetId: nonEmptyString,
      epicId: nonEmptyString,
      workItemIds: stringArray,
      owner: nonEmptyString,
      agentHost: { enum: ["codex", "claude-code", "cursor"] },
      jiraProjectKey: nonEmptyString,
      jiraBoardId: nonEmptyString,
      sprintId: nonEmptyString,
      branchName: nonEmptyString,
      worktreePath: nonEmptyString,
      baseRevision: nonEmptyString,
      affectedPaths: stringArray,
      dependencyIds: stringArray,
      acceptanceBoundary: stringArray,
      targetEnvironment: nonEmptyString,
      pullRequestUrls: stringArray,
    },
  },
  projectProfile: {
    $id: "projectProfile",
    type: "object",
    additionalProperties: false,
    required: [
      "profileId",
      "jiraProjectKey",
      "jiraBoardId",
      "confluenceSpaceKey",
      "githubRepository",
    ],
    properties: {
      profileId: nonEmptyString,
      jiraProjectKey: nonEmptyString,
      jiraBoardId: nonEmptyString,
      confluenceSpaceKey: nonEmptyString,
      githubRepository: nonEmptyString,
    },
  },
  canonicalEvent: {
    $id: "canonicalEvent",
    type: "object",
    additionalProperties: false,
    required: [
      "executionSetId",
      "artifactId",
      "correlationId",
      "source",
      "actor",
      "eventType",
      "sourceRevision",
      "timestamp",
      "beforeState",
      "afterState",
      "evidenceRefs",
      "idempotencyKey",
    ],
    properties: {
      executionSetId: nonEmptyString,
      artifactId: nonEmptyString,
      correlationId: nonEmptyString,
      source: {
        type: "object",
        additionalProperties: false,
        required: ["authority", "canonicalId", "targetIdentity", "requestedOperation"],
        properties: {
          authority: nonEmptyString,
          canonicalId: nonEmptyString,
          targetIdentity: nonEmptyString,
          requestedOperation: nonEmptyString,
        },
      },
      actor: nonEmptyString,
      eventType: nonEmptyString,
      sourceRevision: nonEmptyString,
      timestamp: { type: "string", minLength: 1 },
      beforeState: nonEmptyString,
      afterState: nonEmptyString,
      evidenceRefs: stringArray,
      idempotencyKey: nonEmptyString,
    },
  },
};
