import type { ExecutionEnvelopeInput, ExecutionGraphDraft } from "../../src/execution/types.js";

const referenceRevision = "a".repeat(40);

export const referenceEnvelopeInput: ExecutionEnvelopeInput = {
  contractVersion: "1.0",
  runId: "run-codex-audit-multi",
  goal: "Audit current execution-readiness contracts from repository evidence.",
  scope: ["src/controller", "src/context", "contract/agent-library"],
  nonGoals: ["repository writes", "external sources", "model API access"],
  acceptanceCriteria: [
    { criterionId: "criterion-controller", statement: "Controller assets are traced to exact repository evidence." },
    { criterionId: "criterion-context", statement: "Context and resume assets are traced to exact repository evidence." },
    { criterionId: "criterion-gaps", statement: "Missing capabilities and unknowns remain visible." },
  ],
  sourceRevision: referenceRevision,
  retention: "PERSONAL",
  allowedNodeTypes: ["AGENT_TASK", "DETERMINISTIC_CHECK", "SYNTHESIS"],
  authority: { repositoryWrite: "NONE", externalWrite: "NONE", agentExecution: "CODEX_NATIVE_ONLY" },
  toolScope: ["FILESYSTEM_READ", "LOCAL_SHELL_READ"],
  sources: [{ sourceId: "repo", kind: "REPOSITORY", locator: "AI Booster Kit", sourceRevision: referenceRevision }],
  graphLimits: { maxNodes: 5, maxParallel: 2, maxDepth: 4, maxRepairNodes: 1, maxCheckerRepairCycles: 1 },
  budget: { maxDispatches: 4, maxResultBytes: 131072, maxWallClockMs: 1800000 },
  stopConditions: ["source revision mismatch", "scope violation", "malformed result"],
  requiredEvidenceKinds: ["REPOSITORY_FILE", "ARTIFACT"],
  allowedFinalStates: ["COMPLETE", "COMPLETE_WITH_LIMIT", "STOPPED", "UNKNOWN"],
};

export const referenceGraphDraft: ExecutionGraphDraft = {
  graphId: "graph-codex-audit-multi",
  runId: referenceEnvelopeInput.runId,
  nodes: [
    {
      nodeId: "audit-controller",
      type: "AGENT_TASK",
      required: true,
      state: "PENDING",
      objective: "Inspect Controller, formation, activation, and bounded execution contracts.",
      role: "controller-auditor",
      repairOf: null,
      scope: ["src/controller", "contract/agent-library"],
      prohibitedActions: ["repository writes", "external sources", "agent spawning"],
      contextRefs: [],
      sourceIds: ["repo"],
      toolScope: ["FILESYSTEM_READ", "LOCAL_SHELL_READ"],
      acceptanceCriterionIds: ["criterion-controller", "criterion-gaps"],
    },
    {
      nodeId: "audit-context",
      type: "AGENT_TASK",
      required: true,
      state: "PENDING",
      objective: "Inspect context, persistence, fan-in, checkpoint, and resume contracts.",
      role: "context-auditor",
      repairOf: null,
      scope: ["src/context"],
      prohibitedActions: ["repository writes", "external sources", "agent spawning"],
      contextRefs: [],
      sourceIds: ["repo"],
      toolScope: ["FILESYSTEM_READ", "LOCAL_SHELL_READ"],
      acceptanceCriterionIds: ["criterion-context", "criterion-gaps"],
    },
    {
      nodeId: "checker",
      type: "AGENT_TASK",
      required: true,
      state: "PENDING",
      objective: "Check accepted audit results for completeness, provenance, contradictions, and visible unknowns.",
      role: "evidence-checker",
      repairOf: null,
      scope: ["src/controller", "src/context", "contract/agent-library"],
      prohibitedActions: ["repository writes", "external sources", "agent spawning", "unvalidated worker output"],
      contextRefs: [],
      sourceIds: ["repo"],
      toolScope: ["FILESYSTEM_READ", "LOCAL_SHELL_READ"],
      acceptanceCriterionIds: ["criterion-controller", "criterion-context", "criterion-gaps"],
    },
    {
      nodeId: "synthesis",
      type: "SYNTHESIS",
      required: true,
      state: "PENDING",
      objective: "Create the final readiness and gap handoff from accepted worker and checker artifacts.",
      role: "orchestrator-synthesis",
      repairOf: null,
      scope: ["src/controller", "src/context", "contract/agent-library"],
      prohibitedActions: ["repository writes", "external sources", "agent spawning", "unvalidated worker output"],
      contextRefs: [],
      sourceIds: ["repo"],
      toolScope: ["FILESYSTEM_READ"],
      acceptanceCriterionIds: ["criterion-controller", "criterion-context", "criterion-gaps"],
    },
  ],
  edges: [
    { fromNodeId: "audit-controller", toNodeId: "checker" },
    { fromNodeId: "audit-context", toNodeId: "checker" },
    { fromNodeId: "checker", toNodeId: "synthesis" },
  ],
};
